title: resources.deaf.group
description: This is the place where you can find resources for the deaf and hard of hearing community. They are contributed by individuals.

url: https://resources.deaf.group

theme: just-the-docs

plugins:
  - jekyll-seo-tag
  - jemoji

callouts:
  remember:
    title: Remember this
    color: green
  note:
    title: Note
    color: green
  important:
    title: Important!
    color: blue
  attention:
    title: Attention!
    color: red